### ISSUE TITLE
Build failed 

### ISSUE THREAD

**Issue by sharique** [mono/entityframework#1]
Hi,
## I'm trying to build it from source I get following error.

/opt/mono-dev/mono/external/entityframework/EntityFramework.sln (default targets) ->
(Build target) ->  
/opt/mono-dev/mono/external/entityframework/src/EntityFramework/EntityFramework.csproj (default targets) ->  
/usr/lib/mono/4.0/Microsoft.CSharp.targets (CoreCompile target) ->                                                                                                                                 : error CS2001: Source file `Core/Common/internal/materialization/Coordinator.cs' could not be found
        : error CS2001: Source file`Core/Common/internal/materialization/CoordinatorFactory.cs' could not be found
        : error CS2001: Source file `Core/Common/internal/materialization/Shaper.cs' could not be found
        : error CS2001: Source file`Core/Metadata/Edm/Documentation.cs' could not be found
        : error CS2001: Source file `Core/Metadata/Edm/SafeLink.cs' could not be found
        : error CS2001: Source file`Core/Metadata/Edm/SafeLinkCollection.cs' could not be found
## When looked at this it looks like case sensitive changes, I fixed them by changing names of files. Then I got this error, 

/opt/mono-dev/mono/external/entityframework/EntityFramework.sln (default targets) ->
(Build target) ->
/opt/mono-dev/mono/external/entityframework/src/EntityFramework/EntityFramework.csproj (default targets) ->
/usr/lib/mono/4.0/Microsoft.CSharp.targets (CoreCompile target) ->

```
    Core/Common/CommandTrees/Internal/PatternMatchRule.cs(49,42): error CS1574: Warning as Error: XML comment on `System.Data.Entity.Core.Common.CommandTrees.Internal.PatternMatchRule.Create(System.Func<System.Data.Entity.Core.Common.CommandTrees.DbExpression,bool>, System.Func<System.Data.Entity.Core.Common.CommandTrees.DbExpression,System.Data.Entity.Core.Common.CommandTrees.DbExpression>)' has cref attribute `DbExpressionRule.ProcessedAction.Reset' that could not be resolved
    Core/Objects/Internal/ObjectQueryState.cs(348,41): error CS1574: Warning as Error: XML comment on `System.Data.Entity.Core.Objects.Internal.ObjectQueryState.CreateObjectQuery<TResultType>()' has cref attribute `CreateObjectQuery' that could not be resolved
```

---

I'm also curious about how you sync code between your code base and MS code base.

**Comment by marek-safar** [comment]
This is just fork of Microsoft version it won't build. If you need to build Mono version use mono/mcs/class.EntityFramework
