### ISSUE TITLE
Update or remove?

### ISSUE THREAD

**Issue by Daniel15** [mono/entityframework#3]
Can we please update the version of Entity Framework bundled with Mono, or delete it and let people use their own version from NuGet? I just spent a while debugging an exception (`System.TypeLoadException: Could not load type 'System.Data.Entity.DbConfiguration' from assembly 'EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'`) only to find it was caused by Mono having a super old version of Entity Framework 6 in the GAC. Beta releases shouldn't be GAC'd :-1:

**Comment by akoeplinger** [comment]
This was done a long time ago in Mono 4.0: http://www.mono-project.com/docs/about-mono/releases/4.0.0/#entityframework
